### PR TITLE
Fix whitespace, fix typos, pythonify

### PR DESCRIPTION
**Pull request by SmithChart**
Triggered by a suggestion by @hnez in #3 I've decided to invest some time to prettify the codebase a bit.

* [x] Check on real hardware

### CODE REVIEW

**Comment by jluebbe** [comment]
For a consistent code style I'd suggest to use https://github.com/psf/black.

**Comment by SmithChart** [comment]
> For a consistent code style I'd suggest to use https://github.com/psf/black.

I am not a friend of some suggestions made by _black_. But since my IDE and back keep on changing some lines I'll just accept those changes.
Updated my branch accordingly.

**Comment by hnez** [comment]
Hi,

I've run `black` on even more files and have added some of my own stylistic changes.
I did however not test these changes yet. Someone should do that before merging.

**Comment by hnez** [comment]
Hi,

I've re-spun the pull request. The main change is that the first commit now configures `black` to a line length of 119 characters, adds a hint to use it to the `README.rst` and runs it on all `.py` files.
This remove most formatting changes from the later commits.

**Comment by SmithChart** [comment]
Same here. I've added a few more fixes on top. Mainly based on ``flake8`` findings.
So we should be ready to add ``black`` and ``flake8`` to CI if we want to.

I have tested this version with my USB-Mux and all features still work as expected.

**Pull request merged**
